# ###
# This example relies on the git-clone Task:
# https://github.com/tektoncd/catalog/tree/master/task/git-clone/0.2
#
# ###
#
# This Pipeline will first clone a git repository into a shared workspace.
# The workspace will then be copied to the Orka VM, and the supplied build
# script will be executed inside the VM.
# Build artifacts will then be transferred back to the Tekton workspace,
# which can be consumed by a later Task in the Pipeline, or simply
# saved to a cloud storage bucket.
#
# ###
# Install the git-clone task:
# kubectl apply -f https://raw.githubusercontent.com/tektoncd/catalog/master/task/git-clone/0.2/git-clone.yaml
# ###
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-calcupad-pipeline
spec:
  workspaces:
    - name: shared-data
  tasks:
    - name: fetch-repo
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-data
      params:
        - name: url
          value: https://github.com/kwonye/calcupad.git
        - name: revision
          value: f59faf96b1d45120bc6a3b4ea9e94d4fd67fb9a3
    - name: build-calcupad
      runAfter:
        - fetch-repo
      taskRef:
        name: orka-full
      params:
        - name: base-image
          value: catalina-buildtools-90G.img
        - name: cpu-count
          value: "6"
        - name: vcpu-count
          value: "6"
        - name: verbose
          value: "true"
        - name: script
          value: |
            time xcodebuild CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
      workspaces:
        - name: orka
          workspace: shared-data
    - name: show-build
      runAfter:
        - build-calcupad
      workspaces:
        - name: source
          workspace: shared-data
      taskSpec:
        workspaces:
          - name: source
        steps:
          - name: list
            image: macstadium/orka-tekton-runner:master
            script: |
              #!/bin/sh
              set -ex
              ls -al $(workspaces.source.path)
              ls -al $(workspaces.source.path)/build
              ls -al $(workspaces.source.path)/build/Release-iphoneos
---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: run-build-calcupad-pipeline
spec:
  pipelineRef:
    name: build-calcupad-pipeline
  workspaces:
    - name: shared-data
      volumeClaimTemplate:
        spec:
          storageClassName: manual
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
