# ###
# This example shows how to use the orka-full Task to create a single macOS VM
# on a node with the most-allocated resources.
# The script provided in the params will be executed inside the VM.
#
# You will need to have a secret containing the Orka credentials as well as a
# secret containing the VM SSH credentials as described in the README.
# ###
---
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: target-scheduled-node
spec:
  taskRef:
    name: orka-full
  params:
    - name: base-image
      value: catalina-ssh-30G.img
    - name: copy-build
      value: "false"
    - name: scheduler
      value: "most-allocated" 
    - name: script
      value: |
        echo "Deployed on node with most-allocated resources"
  workspaces:
    - name: orka
      emptyDir: {}
