name: Orka Tekton Release

on:
  workflow_dispatch:
    inputs:
      imageTag:
        description: "Image tag to release (for ex. 0.1-latest)"
        required: true

env:
  GHCR_REPO: ghcr.io/macstadium/orka-tekton-runner

jobs:
  publish:
    if: contains(github.ref, 'refs/heads/releases/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v3
        with:
          ref: ${{github.ref}}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Release Tekton Orka package
        run: |
          set -eux -o pipefail

          IMAGE="$GHCR_REPO:${{ github.event.inputs.imageTag }}"
          RELEASE_IMAGE="$GHCR_REPO:${GITHUB_REF##*/}"

          docker pull $IMAGE
          docker tag $IMAGE $RELEASE_IMAGE
          docker push $RELEASE_IMAGE
