name: tekton-orka-ci

on:
  push:
    paths:
      - .github/workflows/tekton-orka-ci.yaml
      - scripts/**
      - Dockerfile
    branches:
      - jk/OK581-tekton_changes
      - master
      - releases/*

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Deploy image
        run: |
          set -eux

          IMAGE=macstadium/orka-tekton-runner
          IMAGE_TAG=$(date '+%Y-%m-%d')-$(git rev-parse --short=8 HEAD)-${GITHUB_REF##*/}

          docker build --tag $IMAGE:$IMAGE_TAG .
          if [ "$GITHUB_REF" == "refs/heads/master" ]; then
            docker tag $IMAGE:$IMAGE_TAG $IMAGE:master
          else
            docker tag $IMAGE:$IMAGE_TAG $IMAGE:${GITHUB_REF##*/}
          fi
          docker push $IMAGE -a
